### ISSUE TITLE
PAMS_PIN concatenation

### ISSUE THREAD

**Issue by anthonymobile** [code4jc/jcreval#1]
PAMS_PIN concatentation for parcels that have a QCODE (mostly multi-unit parcels like condos)

**Comment by reyale** [comment]
Uh... two columns need to be concatenated?  Not sure the requirement here.   You can element-wise append them like:

data_frame['concated'] = data_frame['col1'] + data_frame['col2']

Best practice is to save them as a new column.

**Comment by anthonymobile** [comment]
its a little bit more complicated. for most properties its a concatenation of 3 fields with underscore separators. 
[countycode][municode]_[blockno]_[lotno]

so for 126A POPLAR ST.: 
0906_702_56 


sometimes, if there is data in Qual Code field, that is tacked on too with another underscore (condos in multi-family buildings mostly)
so for 201 MARIN BLVD.:
0906_15906_8_P0245  


there may also be some additional cleaning to do in order to get the format of PAMS_PIN to line up perfectly with how its coded in the parcel basemap GIS table. but we can add that later, and save it as a third column.

**Comment by reyale** [comment]
OK, what exactly are we trying to get to match?  The above concatenation of PIMS to match against GIS?

**Comment by anthonymobile** [comment]
yes its the PAMS_PIN field in parcels_shp_jc.dbf (I believe) - which is the attributes table for the GIS shapefile. 

then we load our cleaned up assessments.csv and tell the GIS to link them, basically doing a SQL JOIN. then it can lookup values from one for mapping in the other.

the reason to do this a) is the maps will look 1000x better and more informative using the parcel shapes than street address points an b) we get all the spatial analysis tools of QGIS to play with which are substantial (and it has a very robust Python console w/ direct manipulation of map layers + data for whatever else we want to plug in)

i was gonna spend a little time chunking this out today. will see how far i get

**Comment by reyale** [comment]
I can't do it for a few days, but this looks simple.  QGIS is nice, I have used it before. 

BTW, `pd.merge` is what you what to use for your join like functionality.

**Comment by anthonymobile** [comment]
i just threw some code in there that is probably terrible but should show more explicitly what needs to be done.

as far as joining, i let the GIS do all that in the database.

**Comment by anthonymobile** [comment]
ok i made a bunch of progress but am hung up here.

`data_frame['pams_pin_new'] = ('0906_' + data_frame['BlockNo'].map(str) + '_' + str(data_frame['LotNo']) + '_' + data_frame['QualCode(s)'].map(str) )`

the block # expression needs to convert the excel cell to an integer so the .0 gets dropped before conversion to a string. for the lot, i think there are decimal values for some of the rows so im not sure how to handle. might be conditional, need to look at the map table to see how they are there.

then, trying to clean up for the ones that don't have qualcodes and so end up with a trailing underscore from the above...

`data_frame['pams_pin_new'] = data_frame['pams_pin_new'].map(lambda x: x.rstrip('_'))
`

this just doesnt seem to work.

**Comment by reyale** [comment]
I can probably look at this tonight.   Semester ended so some time freed up.  Maybe my son will fall asleep on time tonight.  :-D

**Comment by reyale** [comment]
Also, try:   `data_frame['BlockNo'].astype('int').astype('str')`  Should fix the float->string issue.

**Comment by anthonymobile** [comment]
thanks. + i think i got the other thing working. rstrip needed a space inside the quotes. now to make some maps and wait for the full data dump

**Comment by reyale** [comment]
Cool.  Feel free to add issues here and I'll help out as I can.  Also if you want to meet up I'm generally around this summer.
