### ISSUE TITLE
rfmodel python port

### ISSUE THREAD

**Issue by anthonymobile** [code4jc/jcreval#3]
hey A,
i got a good bit of the way through this before i ran out of steam. think i got most of what i did right...

https://github.com/code4jc/jcreval/blob/master/remodel_port.py.ipynb

**Comment by reyale** [comment]
Probably can't look at this until wednesday, but one thing I can see immediately is that you'll want RandomForestRegressor instead of RandomForestClassifier.

**Comment by anthonymobile** [comment]
mostly done... just one issue i could use a peek at (i think). everything is queued up for inspection, i'm sure i just did something simple and stupid.

**Comment by reyale** [comment]
Well, you didn't do the median replacement.  RF can't work on null/nan values.  Median is a good estimation of a "no information" value for a variable.  Other then that it looks pretty good, I assume the only other issue would be around shaping the input matrix correctly.

**Comment by anthonymobile** [comment]
ah, that's what that was. ill work on it...

**Comment by reyale** [comment]
Logic is roughly: if null replace with median of that column.

**Comment by anthonymobile** [comment]
yes ive seen snippets for it. will find something suitable. thx
